# Generated by Django 5.0.2 on 2024-04-26 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=20)),
                ('abreviatura', models.CharField(max_length=2)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_transaccion', models.CharField(max_length=20)),
                ('abreviatura', models.CharField(max_length=2)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente_Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuenta', models.CharField(max_length=20)),
                ('id_cliente', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='finance.cliente')),
                ('id_producto', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='finance.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.CharField(max_length=20)),
                ('tipo_transaccion', models.CharField(max_length=10)),
                ('id_cliente_producto', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='finance.cliente_producto')),
            ],
        ),
    ]
